server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-odd-shape-aixxmq1s.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_DCNV2A0EPxqc}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:ZDJhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OTA=}
    expiration-ms: 3600000 # 1 Hour
    refresh-expiration-ms: 604800000 # 7 Days

razorpay:
  key: ${RAZORPAY_KEY:rzp_test_ROYjaNT8463J8l}
  secret: ${RAZORPAY_SECRET:LtxDgIEONKZzhefy3XRaGaPt}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:studynotioncloud}
  api-key: ${CLOUDINARY_API_KEY:984143386822821}
  api-secret: ${CLOUDINARY_API_SECRET:YUx_xP7oTPi591xUjSu2LhhEZm0}

